### ISSUE TITLE
Installing new packages with apt-get

### ISSUE THREAD

**Issue by Murmele** [MobileDevOps/android-sdk-image#8]
Is it somehow possible to install other packages with apt-get? I have seen that sudo is not installed and the default user has no root rights

### Which host operation system is used?
- [x] Linux
- [ ] Windows
- [ ] macOS

**Comment by JeppeWiederqvist** [comment]
If you add USER root to the build script you get the root user rights
`
FROM mobiledevops/android-sdk-image:34.0.0
USER root
`

**Comment by Murmele** [comment]
@JEWI-DS thanks for the response. But in this case I have to rebuild the docker image my self and I am not able to use the one at docker.io or am I wrong?

**Comment by JeppeWiederqvist** [comment]
> @JEWI-DS thanks for the response. But in this case I have to rebuild the docker image my self and I am not able to use the one at docker.io or am I wrong?

Well I am running it in a CI script on drone.io, where you just add the USER root as part of your drone pipeline build script :)

**Comment by Murmele** [comment]
Ah ok I understand, I created now my own docker file based on this where I install everything
